export const JSPaths = [
  {
    path: "/javascript/object",
    name: "Objects",
    subPaths: [
      { path: "#constructor", name: "constructor" },
      { path: "#valueOf", name: "valueOf" },
      { path: "#Assign", name: "assign" },
      { path: "#Create", name: "create" },
      { path: "#defineProperties", name: "defineProperties" },
      { path: "#defineProperty", name: "defineProperty" },
      { path: "#entries", name: "entries" },
      { path: "#freeze", name: "freeze" },
      { path: "#fromEntries", name: "fromEntries" },
      { path: "#getOwnPropertyDescriptor", name: "getOwnPropertyDescriptor" },
      { path: "#getOwnPropertyDescriptors", name: "getOwnPropertyDescriptors" },
      { path: "#getOwnPropertyNames", name: "getOwnPropertyNames" },
      { path: "#getOwnPropertySymbols", name: "getOwnPropertySymbols" },
      { path: "#getPrototypeOf", name: "getPrototypeOf" },
      { path: "#hasOwn", name: "hasOwn" },
      { path: "#is", name: "is" },
      { path: "#isExtensible", name: "isExtensible" },
      { path: "#isFrozen", name: "isFrozen" },
      { path: "#isSealed", name: "isSealed" },
      { path: "#keys", name: "keys" },
      { path: "#preventExtensions", name: "preventExtensions" },
      { path: "#seal", name: "seal" },
      { path: "#setPrototypeOf", name: "setPrototypeOf" },
      { path: "#values", name: "values" },
      { path: "#hasOwnProperty", name: "hasOwnProperty" },
      { path: "#isPrototypeOf", name: "isPrototypeOf" },
      { path: "#propertyIsEnumerable", name: "propertyIsEnumerable" },
      { path: "#toLocaleString", name: "toLocaleString" },
      { path: "#toString", name: "toString" },
    ],
  },
  {
    path: "/javascript/async",
    name: "Async",
  },
  {
    path: "/javascript/callback",
    name: "Callback",
  },
  {
    path: "/javascript/promise",
    name: "Promises",
  },
  {
    path: "/javascript/functions",
    name: "Functions",
  },
];
